#include <string>
#include <unordered_map>

using namespace std;

unordered_map<string, unordered_map<string, string>> table = {
    {"<prog>",
     {{"program",
       "program <identifier> ; var <dec-list> begin <stat-list> end"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "blank"},
      {"b", "blank"},
      {"c", "blank"},
      {"d", "blank"},
      {"l", "blank"},
      {"f", "blank"},
      {"0", "blank"},
      {"1", "blank"},
      {"2", "blank"},
      {"3", "blank"},
      {"4", "blank"},
      {"5", "blank"},
      {"6", "blank"},
      {"7", "blank"},
      {"8", "blank"},
      {"9", "blank"},
      {"+", "blank"},
      {"-", "blank"},
      {"*", "blank"},
      {"/", "blank"},
      {"(", "blank"},
      {")", "blank"},
      {"=", "blank"},
      {":", "blank"},
      {";", "blank"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<identifier>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "<letter> <identifier'>"},
      {"b", "<letter> <identifier'>"},
      {"c", "<letter> <identifier'>"},
      {"d", "<letter> <identifier'>"},
      {"l", "<letter> <identifier'>"},
      {"f", "<letter> <identifier'>"},
      {"0", "blank"},
      {"1", "blank"},
      {"2", "blank"},
      {"3", "blank"},
      {"4", "blank"},
      {"5", "blank"},
      {"6", "blank"},
      {"7", "blank"},
      {"8", "blank"},
      {"9", "blank"},
      {"+", "blank"},
      {"-", "blank"},
      {"*", "blank"},
      {"/", "blank"},
      {"(", "blank"},
      {")", "blank"},
      {"=", "blank"},
      {":", "blank"},
      {";", "blank"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<identifier'>",
     {{"program", ""},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "<letter> <identifier’>"},
      {"b", "<letter> <identifier’>"},
      {"c", "<letter> <identifier’>"},
      {"d", "<letter> <identifier’>"},
      {"l", "<letter> <identifier’>"},
      {"f", "<letter> <identifier’>"},
      {"0", "<digit> <identifier’>"},
      {"1", "<digit> <identifier’>"},
      {"2", "<digit> <identifier’>"},
      {"3", "<digit> <identifier’>"},
      {"4", "<digit> <identifier’>"},
      {"5", "<digit> <identifier’>"},
      {"6", "<digit> <identifier’>"},
      {"7", "<digit> <identifier’>"},
      {"8", "<digit> <identifier’>"},
      {"9", "<digit> <identifier’>"},
      {"+", "lambda"},
      {"-", "lambda"},
      {"*", "lambda"},
      {"/", "lambda"},
      {"(", "blank"},
      {")", "lambda"},
      {"=", "lambda"},
      {":", "lambda"},
      {";", "lambda"},
      {",", "lambda"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<dec-list>", {{"program", "blank"},     {"var", "blank"},
                    {"begin", "blank"},       {"end", "blank"},
                    {"integer", "blank"},     {"print", "blank"},
                    {"a", "<dec> : <type>;"}, {"b", "<dec> : <type>;"},
                    {"c", "<dec> : <type>;"}, {"d", "<dec> : <type>;"},
                    {"l", "<dec> : <type>;"}, {"f", "<dec> : <type>;"},
                    {"0", "blank"},           {"1", "blank"},
                    {"2", "blank"},           {"3", "blank"},
                    {"4", "blank"},           {"5", "blank"},
                    {"6", "blank"},           {"7", "blank"},
                    {"8", "blank"},           {"9", "blank"},
                    {"+", "blank"},           {"-", "blank"},
                    {"*", "blank"},           {"/", "blank"},
                    {"(", "blank"},           {")", "blank"},
                    {"=", "blank"},           {":", "blank"},
                    {";", "blank"},           {",", "blank"},
                    {"\"", "blank"},          {"$", "blank"}}},
    {"<dec>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "<identifier> <dec'>"},
      {"b", "<identifier> <dec'>"},
      {"c", "<identifier> <dec'>"},
      {"d", "<identifier> <dec'>"},
      {"l", "<identifier> <dec'>"},
      {"f", "<identifier> <dec'>"},
      {"0", "blank"},
      {"1", "blank"},
      {"2", "blank"},
      {"3", "blank"},
      {"4", "blank"},
      {"5", "blank"},
      {"6", "blank"},
      {"7", "blank"},
      {"8", "blank"},
      {"9", "blank"},
      {"+", "blank"},
      {"-", "blank"},
      {"*", "blank"},
      {"/", "blank"},
      {"(", "blank"},
      {")", "blank"},
      {"=", "blank"},
      {":", "blank"},
      {";", "blank"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<dec'>", {{"program", "blank"}, {"var", "blank"},
                {"begin", "blank"},   {"end", "blank"},
                {"integer", "blank"}, {"print", "blank"},
                {"a", "blank"},       {"b", "blank"},
                {"c", "blank"},       {"d", "blank"},
                {"l", "blank"},       {"f", "blank"},
                {"0", "blank"},       {"1", "blank"},
                {"2", "blank"},       {"3", "blank"},
                {"4", "blank"},       {"5", "blank"},
                {"6", "blank"},       {"7", "blank"},
                {"8", "blank"},       {"9", "blank"},
                {"+", "blank"},       {"-", "blank"},
                {"*", "blank"},       {"/", "blank"},
                {"(", "blank"},       {")", "blank"},
                {"=", "blank"},       {":", "blank"},
                {";", "blank"},       {",", ",<identifier> <dec’>"},
                {"\"", "blank"},      {"$", "blank"}}},
    {"<type>",
     {{"program", "blank"}, {"var", "blank"},       {"begin", "blank"},
      {"end", "blank"},     {"integer", "integer"}, {"print", "blank"},
      {"a", "blank"},       {"b", "blank"},         {"c", "blank"},
      {"d", "blank"},       {"l", "blank"},         {"f", "blank"},
      {"0", "blank"},       {"1", "blank"},         {"2", "blank"},
      {"3", "blank"},       {"4", "blank"},         {"5", "blank"},
      {"6", "blank"},       {"7", "blank"},         {"8", "blank"},
      {"9", "blank"},       {"+", "blank"},         {"-", "blank"},
      {"*", "blank"},       {"/", "blank"},         {"(", "blank"},
      {")", "blank"},       {"=", "blank"},         {":", "blank"},
      {";", "blank"},       {",", "blank"},         {"\"", "blank"},
      {"$", "blank"}}},
    {"<stat-list>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "<stat> <stat-list'>"},
      {"a", "<stat> <stat-list'>"},
      {"b", "<stat> <stat-list'>"},
      {"c", "<stat> <stat-list'>"},
      {"d", "<stat> <stat-list'>"},
      {"l", "<stat> <stat-list'>"},
      {"f", "<stat> <stat-list'>"},
      {"0", "blank"},
      {"1", "blank"},
      {"2", "blank"},
      {"3", "blank"},
      {"4", "blank"},
      {"5", "blank"},
      {"6", "blank"},
      {"7", "blank"},
      {"8", "blank"},
      {"9", "blank"},
      {"+", "blank"},
      {"-", "blank"},
      {"*", "blank"},
      {"/", "blank"},
      {"(", "blank"},
      {")", "blank"},
      {"=", "blank"},
      {":", "blank"},
      {";", "blank"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<stat-list'>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "lambda"},
      {"integer", "blank"},
      {"print", "<stat> <stat-list'>"},
      {"a", "<stat> <stat-list'>"},
      {"b", "<stat> <stat-list'>"},
      {"c", "<stat> <stat-list'>"},
      {"d", "<stat> <stat-list'>"},
      {"l", "<stat> <stat-list'>"},
      {"f", "<stat> <stat-list'>"},
      {"1", "blank"},
      {"2", "blank"},
      {"3", "blank"},
      {"4", "blank"},
      {"5", "blank"},
      {"6", "blank"},
      {"7", "blank"},
      {"8", "blank"},
      {"9", "blank"},
      {"+", "blank"},
      {"-", "blank"},
      {"*", "blank"},
      {"/", "blank"},
      {"(", "blank"},
      {")", "blank"},
      {"=", "blank"},
      {":", "blank"},
      {";", "blank"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<stat>",
     {{"program", "blank"}, {"var", "blank"},     {"begin", "blank"},
      {"end", "blank"},     {"integer", "blank"}, {"print", "<write>"},
      {"a", "<assign>"},    {"b", "<assign>"},    {"c", "<assign>"},
      {"d", "<assign>"},    {"l", "<assign>"},    {"f", "<assign>"},
      {"0", "blank"},       {"1", "blank"},       {"2", "blank"},
      {"3", "blank"},       {"4", "blank"},       {"5", "blank"},
      {"6", "blank"},       {"7", "blank"},       {"8", "blank"},
      {"9", "blank"},       {"+", "blank"},       {"-", "blank"},
      {"*", "blank"},       {"/", "blank"},       {"(", "blank"},
      {")", "blank"},       {"=", "blank"},       {":", "blank"},
      {";", "blank"},       {",", "blank"},       {"\"", "blank"},
      {"$", "blank"}}},
    {"<write>", {{"program", "blank"}, {"var", "blank"},
                 {"begin", "blank"},   {"end", "blank"},
                 {"integer", "blank"}, {"print", "print ( <write'> )"},
                 {"a", "blank"},       {"b", "blank"},
                 {"c", "blank"},       {"d", "blank"},
                 {"l", "blank"},       {"f", "blank"},
                 {"0", "blank"},       {"1", "blank"},
                 {"2", "blank"},       {"3", "blank"},
                 {"4", "blank"},       {"5", "blank"},
                 {"6", "blank"},       {"7", "blank"},
                 {"8", "blank"},       {"9", "blank"},
                 {"+", "blank"},       {"-", "blank"},
                 {"*", "blank"},       {"/", "blank"},
                 {"(", "blank"},       {")", "lambda"},
                 {"=", "blank"},       {":", "blank"},
                 {";", "blank"},       {",", "blank"},
                 {"\"", "blank"},      {"$", "blank"}}},
    {"<write'>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "<str> <identifier>"},
      {"b", "<str> <identifier>"},
      {"c", "<str> <identifier>"},
      {"d", "<str> <identifier>"},
      {"l", "<str> <identifier>"},
      {"f", "<str> <identifier>"},
      {"0", "blank"},
      {"1", "blank"},
      {"2", "blank"},
      {"3", "blank"},
      {"4", "blank"},
      {"5", "blank"},
      {"6", "blank"},
      {"7", "blank"},
      {"8", "blank"},
      {"9", "blank"},
      {"+", "blank"},
      {"-", "blank"},
      {"*", "blank"},
      {"/", "blank"},
      {"(", "blank"},
      {")", "blank"},
      {"=", "blank"},
      {":", "blank"},
      {";", "blank"},
      {",", "blank"},
      {"\"", "<str> <identifier>"},
      {"$", "blank"}}},
    {"<str>",
     {{"program", "blank"}, {"var", "blank"},     {"begin", "blank"},
      {"end", "blank"},     {"integer", "blank"}, {"print", "blank"},
      {"a", "lambda"},      {"b", "lambda"},      {"c", "lambda"},
      {"d", "lambda"},      {"l", "lambda"},      {"f", "lambda"},
      {"0", "blank"},       {"1", "blank"},       {"2", "blank"},
      {"3", "blank"},       {"4", "blank"},       {"5", "blank"},
      {"6", "blank"},       {"7", "blank"},       {"8", "blank"},
      {"9", "blank"},       {"+", "blank"},       {"-", "blank"},
      {"*", "blank"},       {"/", "blank"},       {"(", "blank"},
      {")", "blank"},       {"=", "blank"},       {":", "blank"},
      {";", "blank"},       {",", "blank"},       {"\"", "\"value=\","},
      {"$", "blank"}}},
    {"<assign>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "<identifier> = <expr>;"},
      {"b", "<identifier> = <expr>;"},
      {"c", "<identifier> = <expr>;"},
      {"d", "<identifier> = <expr>;"},
      {"l", "<identifier> = <expr>;"},
      {"f", "<identifier> = <expr>;"},
      {"0", "blank"},
      {"1", "blank"},
      {"2", "blank"},
      {"3", "blank"},
      {"4", "blank"},
      {"5", "blank"},
      {"6", "blank"},
      {"7", "blank"},
      {"8", "blank"},
      {"9", "blank"},
      {"+", "blank"},
      {"-", "blank"},
      {"*", "blank"},
      {"/", "blank"},
      {"(", "blank"},
      {")", "blank"},
      {"=", "blank"},
      {":", "blank"},
      {";", "blank"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<expr>",
     {{"program", "blank"},    {"var", "blank"},        {"begin", "blank"},
      {"end", "blank"},        {"integer", "blank"},    {"print", "blank"},
      {"a", "<term> <expr'>"}, {"b", "<term> <expr'>"}, {"c", "<term> <expr'>"},
      {"d", "<term> <expr'>"}, {"l", "<term> <expr'>"}, {"f", "<term> <expr'>"},
      {"0", "<term> <expr'>"}, {"1", "<term> <expr'>"}, {"2", "<term> <expr'>"},
      {"3", "<term> <expr'>"}, {"4", "<term> <expr'>"}, {"5", "<term> <expr'>"},
      {"6", "<term> <expr'>"}, {"7", "<term> <expr'>"}, {"8", "<term> <expr'>"},
      {"9", "<term> <expr'>"}, {"+", "<term> <expr'>"}, {"-", "<term> <expr'>"},
      {"*", "blank"},          {"/", "blank"},          {"(", "<term> <expr'>"},
      {")", "lambda"},         {"=", "blank"},          {":", "blank"},
      {";", "lambda"},         {",", "blank"},          {"\"", "blank"},
      {"$", "blank"}}},
    {"<expr'>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "blank"},
      {"b", "blank"},
      {"c", "blank"},
      {"d", "blank"},
      {"l", "blank"},
      {"f", "blank"},
      {"0", "blank"},
      {"1", "blank"},
      {"2", "blank"},
      {"3", "blank"},
      {"4", "blank"},
      {"5", "blank"},
      {"6", "blank"},
      {"7", "blank"},
      {"8", "blank"},
      {"9", "blank"},
      {"+", "+ <term> <expr’>"},
      {"-", "- <term> <expr’>"},
      {"*", "blank"},
      {"/", "blank"},
      {"(", "blank"},
      {")", "lambda"},
      {"=", "blank"},
      {":", "blank"},
      {";", "lambda"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<term>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "<factor> <term’>"},
      {"b", "<factor> <term’>"},
      {"c", "<factor> <term’>"},
      {"d", "<factor> <term’>"},
      {"l", "<factor> <term’>"},
      {"f", "<factor> <term’>"},
      {"0", "<factor> <term’>"},
      {"1", "<factor> <term’>"},
      {"2", "<factor> <term’>"},
      {"3", "<factor> <term’>"},
      {"4", "<factor> <term’>"},
      {"5", "<factor> <term’>"},
      {"6", "<factor> <term’>"},
      {"7", "<factor> <term’>"},
      {"8", "<factor> <term’>"},
      {"9", "<factor> <term’>"},
      {"+", "<factor> <term’>"},
      {"-", "<factor> <term’>"},
      {"*", "blank"},
      {"/", "blank"},
      {"(", "<factor> <term’>"},
      {")", "lambda"},
      {"=", "blank"},
      {":", "blank"},
      {";", "lambda"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<term'>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "blank"},
      {"b", "blank"},
      {"c", "blank"},
      {"d", "blank"},
      {"l", "blank"},
      {"f", "blank"},
      {"0", "blank"},
      {"1", "blank"},
      {"2", "blank"},
      {"3", "blank"},
      {"4", "blank"},
      {"5", "blank"},
      {"6", "blank"},
      {"7", "blank"},
      {"8", "blank"},
      {"9", "blank"},
      {"+", "lambda"},
      {"-", "lambda"},
      {"*", "* <factor> <term'>"},
      {"/", "/ <factor> <term'>"},
      {"(", "blank"},
      {")", "lambda"},
      {"=", "blank"},
      {":", "blank"},
      {";", "lambda"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<factor>",
     {{"program", "blank"},  {"var", "blank"},      {"begin", "blank"},
      {"end", "blank"},      {"integer", "blank"},  {"print", "blank"},
      {"a", "<identifier>"}, {"b", "<identifier>"}, {"c", "<identifier>"},
      {"d", "<identifier>"}, {"l", "<identifier>"}, {"f", "<identifier>"},
      {"0", "<number>"},     {"1", "<number>"},     {"2", "<number>"},
      {"3", "<number>"},     {"4", "<number>"},     {"5", "<number>"},
      {"6", "<number>"},     {"7", "<number>"},     {"8", "<number>"},
      {"9", "<number>"},     {"+", "lambda"},       {"-", "lambda"},
      {"*", "blank"},        {"/", "blank"},        {"(", "( <expr> )"},
      {")", "lambda"},       {"=", "blank"},        {":", "blank"},
      {";", "lambda"},       {",", "blank"},        {"\"", "blank"},
      {"$", "blank"}}},
    {"<number>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "blank"},
      {"b", "blank"},
      {"c", "blank"},
      {"d", "blank"},
      {"l", "blank"},
      {"f", "blank"},
      {"0", "<sign> <digit> <number'>"},
      {"1", "<sign> <digit> <number'>"},
      {"2", "<sign> <digit> <number'>"},
      {"3", "<sign> <digit> <number'>"},
      {"4", "<sign> <digit> <number'>"},
      {"5", "<sign> <digit> <number'>"},
      {"6", "<sign> <digit> <number'>"},
      {"7", "<sign> <digit> <number'>"},
      {"8", "<sign> <digit> <number'>"},
      {"9", "<sign> <digit> <number'>"},
      {"+", "<sign> <digit> <number'>"},
      {"-", "<sign> <digit> <number'>"},
      {"*", "lambda"},
      {"/", "lambda"},
      {"(", "blank"},
      {")", "lambda"},
      {"=", "blank"},
      {":", "blank"},
      {";", "lambda"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<number'>",
     {{"program", "blank"},
      {"var", "blank"},
      {"begin", "blank"},
      {"end", "blank"},
      {"integer", "blank"},
      {"print", "blank"},
      {"a", "blank"},
      {"b", "blank"},
      {"c", "blank"},
      {"d", "blank"},
      {"l", "blank"},
      {"f", "blank"},
      {"0", "<digit> <number’>"},
      {"1", "<digit> <number’>"},
      {"2", "<digit> <number’>"},
      {"3", "<digit> <number’>"},
      {"4", "<digit> <number’>"},
      {"5", "<digit> <number’>"},
      {"6", "<digit> <number’>"},
      {"7", "<digit> <number’>"},
      {"8", "<digit> <number’>"},
      {"9", "<digit> <number’>"},
      {"+", "lambda"},
      {"-", "lambda"},
      {"*", "lambda"},
      {"/", "lambda"},
      {"(", "blank"},
      {")", "lambda"},
      {"=", "blank"},
      {":", "blank"},
      {";", "lambda"},
      {",", "blank"},
      {"\"", "blank"},
      {"$", "blank"}}},
    {"<sign>", {{"program", "blank"}, {"var", "blank"},     {"begin", "blank"},
                {"end", "blank"},     {"integer", "blank"}, {"print", "blank"},
                {"a", "blank"},       {"b", "blank"},       {"c", "blank"},
                {"d", "blank"},       {"l", "blank"},       {"f", "blank"},
                {"0", "lambda"},      {"1", "lambda"},      {"2", "lambda"},
                {"3", "lambda"},      {"4", "lambda"},      {"5", "lambda"},
                {"6", "lambda"},      {"7", "lambda"},      {"8", "lambda"},
                {"9", "lambda"},      {"+", "+"},           {"-", "-"},
                {"*", "blank"},       {"/", "blank"},       {"(", "blank"},
                {")", "blank"},       {"=", "blank"},       {":", "blank"},
                {";", "blank"},       {",", "blank"},       {"\"", "blank"},
                {"$", "blank"}}},
    {"<digit>", {{"program", "blank"}, {"var", "blank"},     {"begin", "blank"},
                 {"end", "blank"},     {"integer", "blank"}, {"print", "blank"},
                 {"a", "blank"},       {"b", "blank"},       {"c", "blank"},
                 {"d", "blank"},       {"l", "blank"},       {"f", "blank"},
                 {"0", "0"},           {"1", "1"},           {"2", "2"},
                 {"3", "3"},           {"4", "4"},           {"5", "5"},
                 {"6", "6"},           {"7", "7"},           {"8", "8"},
                 {"9", "9"},           {"+", "blank"},       {"-", "blank"},
                 {"*", "blank"},       {"/", "blank"},       {"(", "blank"},
                 {")", "blank"},       {"=", "blank"},       {":", "blank"},
                 {";", "blank"},       {",", "blank"},       {"\"", "blank"},
                 {"$", "blank"}}},
    {"<letter>",
     {{"program", "blank"}, {"var", "blank"},     {"begin", "blank"},
      {"end", "blank"},     {"integer", "blank"}, {"print", "blank"},
      {"a", "a"},           {"b", "b"},           {"c", "c"},
      {"d", "d"},           {"l", "l"},           {"f", "f"},
      {"0", "blank"},       {"1", "blank"},       {"2", "blank"},
      {"3", "blank"},       {"4", "blank"},       {"5", "blank"},
      {"6", "blank"},       {"7", "blank"},       {"8", "blank"},
      {"9", "blank"},       {"+", "blank"},       {"-", "blank"},
      {"*", "blank"},       {"/", "blank"},       {"(", "blank"},
      {")", "blank"},       {"=", "blank"},       {":", "blank"},
      {";", "blank"},       {",", "blank"},       {"\"", "blank"},
      {"$", "blank"}}}};
